---

- name: Ensure expect is installed
  apt:
    name: expect
    state: present
  when: ravendb.rvn.trust_client_cert is defined

- name: Trust client certificate
  shell: |
    set timeout 300
    spawn /opt/RavenDB/Server/rvn admin-channel
    expect "ravendb>"
    send "trustClientCert client {{ ravendb.rvn.trust_client_cert }}\n"
    expect "ravendb>"
    send "logout\n"
    interact
    exit 0
  args:
    executable: /usr/bin/expect
  when: ravendb.rvn.trust_client_cert is defined